### ISSUE TITLE
document.write makes selenium-client hang

### ISSUE THREAD

**Issue by tomjack** [ph7/selenium-client#1]
I made a simple test using document.write('Hello!') to make sure cucumber/webrat/selenium was working. Selenium starts up, navigates to the page, and then hangs. Took me several hours to realize the problem was document.write.

I wouldn't use document.write in a real app anyway, but it seems strange that selenium-client can't handle it.

This was on Mac OS 10.5.6, Firefox 3.0.10 and Safari 3.1.2, and selenium-client 1.2.14. I'm not sure if this is a selenium-client or selenium-rc bug.

**Comment by ph7** [comment]
Not enough details to meaningfully analyze this bug + likely to be a bug in RC if it is indeed a bug
