### ISSUE TITLE
Why does selenium client 1.2.17 require rspec 1.2.8 but selenium grid require rspec 1.1.8?

### ISSUE THREAD

**Issue by scottcsims** [ph7/selenium-client#10]
I am trying to use the latest version of the selenium client with the selenium grid.  I know that deep test requires rspec 1.1.8 because it overrides spec task in rspec.  I am having trouble managing my rspec gem versions because I must have 1.1.8 for deep test and the grid, but the selenium client has gem "rspec", "=1.2.8" in a few places.

**Comment by ph7** [comment]
Your analysis is correct. The only reason is DeepTest. You might want to contribute a patch to DeepTest to enable RSpec 1.2.8 support.

**Comment by scottcsims** [comment]
I will look in to contributing a patch to DeepTest. I did some research on the deep test gem and found out that the last time it was packaged was 2007.  I was able to get the deep test source from github and use it instead of the gem.  The current deep test source is using rspec 1.1.12 so that solved my problem for now.
