### ISSUE TITLE
"ed out after 5000 msec"

### ISSUE THREAD

**Issue by alexch** [ph7/selenium-client#11]
selenium-client has a bug where if the response doesn't start with
"OK" it swallows the first three chars (leading to annoying "ed
out after 5000 msec" messages)

I've fixed it on my local machine; I think I'll go make a fork and fix it there. Check http://github.com/alexch/selenium-client and see if I've done it yet :-)

**Comment by ph7** [comment]
Hi Alex, thanks for the bug report and the fix. I have merged your patch into master and will release it soon as part of selenium-client 1.2.18. Thanks again!
