### ISSUE TITLE
submit method fails

### ISSUE THREAD

**Issue by raldred** [ph7/selenium-client#12]
using a valid for id i receive the following error

(rdb:1) selenium.submit('purchase_order_payment')
Selenium::CommandError Exception: OR: Command execution failure. Please search the forum at http://clearspace.openqa.org for error details from the log window.  The error message is: formElement.submit is not a function

**Comment by ph7** [comment]
There is not enough details included to provide meaningful feedback. Additionally, based on the description the problem is likely to be either with the test logic or Selenium Core, not selenium-client.

**Comment by raldred** [comment]
No problem, you are correct its an issue with selenium-core
