### ISSUE TITLE
Unable to startup mongrel (gem_path issues?)

### ISSUE THREAD

**Issue by rwdaigle** [ph7/selenium-client#13]
This issue smells a lot like a configuration issue on my end, but I've dug as far as I can and am still seeing this issue:

When running selenium tests via cucumber/webrat the selenium RC server starts up fine, but mongrel is unable to start (it can't find the gem).  Here is the output:

testing app$ cucumber -p selenium
Using the selenium profile...
Feature: User authentication
  In order to use the site
  I need to be able to authenticate myself

  @selenium
  Scenario: User login                                               # features/user_authentication.feature:45
    Given a user exists with username: "ryand", password: "PASSWOrd" # features/step_definitions/pickle_steps.rb:4
==> Waiting for Selenium RC server on port 4444... Ready!
==> Waiting for rails application server on port 3001... /Library/Ruby/Site/1.8/rubygems.rb:827:in `report_activate_error': Could not find RubyGem mongrel (>= 0) (Gem::LoadError)
        from /Library/Ruby/Site/1.8/rubygems.rb:261:in`activate'
        from /Library/Ruby/Site/1.8/rubygems.rb:68:in `gem'
        from /usr/bin/mongrel_rails:18

Rest assured, mongrel is installed on my machine, as executing the following executes without issue:

testing app$ mongrel_rails start --chdir='/Users/ryan/dev/app' --port=3001 --environment=selenium --pid /Users/ryan/dev/app/tmp/pids/mongrel_selenium.pid
*\* Starting Mongrel listening at 0.0.0.0:3001
*\* Starting Rails with selenium environment...
[DEPRECATION] Paperclip::Attachment.interpolations is deprecated and will be removed from future versions. Use Paperclip.interpolates instead
*\* Rails loaded.
*\* Loading any Rails specific GemPlugins
*\* Signals ready.  TERM => stop.  USR2 => restart.  INT => stop (no restart).
*\* Rails signals registered.  HUP => reload (without restart).  It might not work well.
*\* Mongrel 1.1.5 available at 0.0.0.0:3001
*\* Use CTRL-C to stop.

So somehow, when run via the selenium command, the mongrel gem is not being found.  Is there anything funky happening with the GEM_PATH when selenium-client tries to boot mongrel?  This makes it look like it's being cleared, though I'm sure nothing that obvious is happening.

**Comment by ph7** [comment]
Seems like a Mongrel/Cucumber issue not a selenium-client problem per say...
