### ISSUE TITLE
XHR ERROR on open command

### ISSUE THREAD

**Issue by sonomarob** [ph7/selenium-client#16]
When trying to open some urls via selenium-server-1.0.3, the open fails with a 404 or 500 and an XHR Error.

This is documented on the google code site for selenium: http://code.google.com/p/selenium/issues/detail?id=408

I have worked around this by substituting open method calls that fail like driver.open("http://mail.google.com") with the direct call and an additional parameter:
driver.remote_control_command("open", ["http://mail.google.com/","true"])

This should probably be fixed in the server and likely not worth patching in the client, but I thought I would post this workaround here.

**Comment by ph7** [comment]
Thanks for the heads up!

**Comment by rogerkk** [comment]
And another thanks. Saved my day. :)
