### ISSUE TITLE
Not able to start RC using the code

### ISSUE THREAD

**Issue by deepakr** [ph7/selenium-client#2]
Sir,

Please help , I am not able to start RC using following code.
require "rubygems"
require "selenium-client" 
require "selenium/rake/tasks"
class Newtest
Selenium::Rake::RemoteControlStartTask.new do |rc|
  rc.port = 4444
  rc.timeout_in_seconds = 3 \* 60
  rc.background = true
  rc.wait_until_up_and_running = true
  rc.jar_file = ""
  rc.additional_args << "-singleWindow"
end 
end

error :: ruby: No such file or directory -- run (LoadError)

**Comment by aptinio** [comment]
try:
    require "selenium/client"
instead of:
    require "selenium-client"

**Comment by ph7** [comment]
Not a bug. You need to either:

gem 'selenium-client'

or

require "selenium/client"
