### ISSUE TITLE
Point at googlecode

### ISSUE THREAD

**Issue by nirvdrum** [ph7/selenium-client#30]
Hi Philippe,

Jari integrated the Selenium RC ruby bindings in the selenium-webclient gem a while ago.  Since these are kept up-to-date, would you mind updating your README to just point at those?

**Comment by ph7** [comment]
Sure what is a good url?

**Comment by nirvdrum** [comment]
Actually, the RubyGems page is probably the best, since it has links for download, the docs, the home page, issue tracker, and so on.

http://rubygems.org/gems/selenium-webdriver

Thanks!

**Comment by ph7** [comment]
Done

**Comment by ph7** [comment]
Done
