### ISSUE TITLE
Ruby Client passes timeout as 3000030000300000... to selenium-rc for wait_for_page_to_load

### ISSUE THREAD

**Issue by ericbeland** [ph7/selenium-client#5]
Selenium-ide generated ruby scripts are not usable out of the box in the Ruby Client-driver due to a discrepancy in wait_for_page_to_load.  Previously this conflict did not occur (in version 1.2.9)

Selenium-ide generates scripts with the following style for navigations:

   @selenium.click "link=Linux Commands"
   @selenium.wait_for_page_to_load "30000"

Currently, the wait_for_page_to_load command utilizes a string in milliseconds, not seconds.  The Ruby client doc is not explicit as to the required argument-type.

In the ruby client driver, currently when Idiomatic.rb is loaded, the base definition of wait_for_page_to_load is reset using alias_method from the original definition found in
generated_driver.rb to the idiomatic driver's wait_for_page method instead:

idiomatic.rb:48

```
 def wait_for_page(timeout_in_seconds=nil)
   actual_timeout = timeout_in_seconds || default_timeout_in_seconds
   remote_control_command "waitForPageToLoad", [actual_timeout * 1000,]
 end
 alias_method :wait_for_page_to_load, :wait_for_page
```

The idiomatic driver expects a timeout in seconds, not milliseconds, so the \* 1000 is needed for the conversion.

The net effect of using a selenium-ide generated script currently is that the string "30000" in wait_for_page_to_load  in the example above is used in the  actual_timeout \* 1000  calculation, and so the timeout value passed to selenium-rc is a string of the characters "30000" repeated 1000 times.

**Comment by ph7** [comment]
Fixed in selenium-client 1.2.17
