### ISSUE TITLE
New feature: wait_for_visible method

### ISSUE THREAD

**Issue by eliotsykes** [ph7/selenium-client#6]
Would like to put forward new wait_for_visible method to add to selenium-client

**Comment by eliotsykes** [comment]
In javascript_expression_builder.rb, add this method:
      def visible(locator)
        append "selenium.isVisible('#{quote_escaped(locator)}')"
      end

In extensions.rb, add this method:
    def wait_for_visible(locator, options={})
        builder = JavascriptExpressionBuilder.new 
        wait_for_condition builder.visible(locator).script, options[:timeout_in_seconds]
      end

**Comment by ph7** [comment]
Added to the selenium-client gem

**Comment by eliotsykes** [comment]
Great :)
