### ISSUE TITLE
Does selenium-client support Ruby 1.9?

### ISSUE THREAD

**Issue by latasoy** [ph7/selenium-client#9]
It has been working perfectly for me for 1.8. Recently I tried 1.9 to take advantage of some debug/speed improvements. Most of the code was compatible, but a few seem to have differences, mainly on Process and Net/HTTP area. The selenium remote control code seemed not to work with it. Is is expected to work? If not, what are the plans for future?

BTW, many thanks for the great software that was pleasure to work with.

**Comment by ph7** [comment]
Hi,

Thank you for your kind words.

selenium-client releases >= 1.2.16 are compatible with Ruby 1.9.1 . To the best of my knowledge everything is working fine and the integration build (rake ci:integration) is green on MRI 1.9.1. Do you have more specific issues/bugs you can point at/reproduce?

Thanks in advance,
- Philippe
